version: "3"

services:
  proxy:
    image: unblee/mirror:latest
    ports:
      - "80:5000"
    environment:
      - LISTEN_PORT=5000
      - DEFAULT_DEST_PORT=80
      - BASE_DOMAIN=127.0.0.1.xip.io
      - DEFAULT_DEST_URL=http://default:8080
      - DB_HOST=redis
      - DB_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - "6379"

  rcli:
    image: redis:alpine
    command: sh -c "redis-cli -h redis HSET mirror-store dest1 http://dest1; redis-cli -h redis HSET mirror-store dest2 http://dest2:8080/{}"
    depends_on:
      - redis

  dest1:
    image: golang:alpine
    environment:
      - PORT=80
    volumes:
      - .:/go/src
    expose:
      - "80"
    command: ["go", "run", "/go/src/exampleDestServer.go"]

  dest2:
    image: golang:alpine
    environment:
      - PORT=8080
    volumes:
      - .:/go/src
    expose:
      - "8080"
    command: ["go", "run", "/go/src/exampleDestServer.go"]

  default:
    image: golang:alpine
    environment:
      - PORT=8080
    volumes:
      - .:/go/src
    expose:
      - "8080"
    command: ["go", "run", "/go/src/exampleDestServer.go"]